stages:
  - puml
  - dotnet

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never

puml:pipeline:
  stage: puml
  trigger:
    include:
      - local: .gitlab/.gitlab-ci.puml.yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID

dotnet:pipeline:
  stage: dotnet
  trigger:
    include:
      - local: .gitlab/.gitlab-ci.dotnet.yml
    strategy: depend
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID