@startuml C4_Elements
!include ./template_c4.puml

Person(personAlias, "User", "Optional Description")
Container(containerAlias, "Label", "Technology", "Optional Description")
System(systemAlias, "Label", "Optional Description")

Rel(personAlias, containerAlias, "Label", "Optional Technology")
Rel(personAlias, systemAlias, "Destroying", "RUST")
@enduml